packaging_format = 2

id = "kitchenowl"
name = "KitchenOwl"
description.en = "Self-hosted grocery list and recipe manager"
description.fr = "Gestionnaire de listes de courses et de recettes auto-hébergé"

version = "0.4.7~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://kitchenowl.org/"
demo = "https://app.kitchenowl.org/"
admindoc = "https://docs.kitchenowl.org/"
userdoc = "https://docs.kitchenowl.org/getting-started/tips-and-tricks/"
code = "https://github.com/TomBursch/kitchenowl"
fund = "https://github.com/sponsors/TomBursch"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kitchenowl"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.main]

        url = "https://github.com/TomBursch/kitchenowl/releases/download/v0.6.11/kitchenowl_Web.tar.gz"
        sha256 = "7cb7acecc0d70f77f26c69eec5725620d3c945b6b4433953fff6457de03551a4"
        
    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
   
    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    #[resources.ports]

    #[resources.apt]
    #packages = "postgresql, postgresql-contrib"

    #[resources.database]
    #type = "postgresql"
