#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MAKE INSTALL
#=================================================
ynh_script_progression "Making install..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration..."

#key=$(ynh_string_random --length=45 | base64)
#ynh_app_setting_set --key=key --value=$key

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
#ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
#ynh_config_add_logrotate

#yunohost service add $app --description="KitchenOwl main service" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
#ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
