#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# CONFIGURE THE INSTALL SCRIPT
#=================================================

ynh_script_progression --message="Adding a configuration file..."

ynh_setup_source --dest_dir="$install_dir/frontapi" --source_id="front"
ynh_setup_source --dest_dir="$install_dir/backend" --source_id="backend"

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --app=$app --key=key --value=$key

ynh_add_config --template="../conf/.env" --destination="$install_dir/.env"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chmod 600 "$install_dir/.env"

chown -R $app:www-data "$install_dir"
chown $app:$app "$install_dir/.env"

set -a; source "$install_dir/.env"; set +a

#=================================================
# SPECIFIC SETUP
#=================================================

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing Python dependencies..." --weight=3

pushd $install_dir
	python3 -m venv $install_dir/backend/venv
	source $install_dir/backend/venv/bin/activate
	ynh_exec_warn_less pip3 install -r requirements.txt
popd

#=================================================
# CREATE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Creating a data directory..."

chmod 750 "$data_dir"
chmod -R o-rwx "$data_dir"
chown -R $app:www-data "$data_dir"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..."

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add $app --description="KitchenOwl main service" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_exec_warn_less ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
